# Generated by Django 4.2.16 on 2025-01-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_user_alter_order_customer_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
