# Generated by Django 4.2.16 on 2025-02-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_alter_order_customer_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_cateogiry',
            new_name='name_category',
        ),
    ]
