# Generated by Django 4.2.16 on 2025-02-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_rename_name_cateogiry_category_name_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories_img/'),
        ),
    ]
